export const redirects = [
  { source: "/media", destination: "/blog", permanent: true },
  { source: "/developers", destination: "/developer", permanent: true },
  { source: "/home-loans", destination: "/", permanent: true },
  { source: "/developer/elan-group", destination: "/developer/", permanent: true },
  { source: "/developer/silverglades-group", destination: "/developer/", permanent: true },
  { source: "/developer/nyati-group", destination: "/developer/", permanent: true },
  { source: "/blog/category/blogs", destination: "/blog/", permanent: true },
  { source: "/developer/spectrum-realty", destination: "/developer/", permanent: true },
  { source: "/developer/smartworld-developers", destination: "/developer/", permanent: true },
  { source: "/developer/goyal-properties", destination: "/developer/", permanent: true },
  { source: "/developer/kunal-group", destination: "/developer/", permanent: true },
  { source: "/developer/lt-realty", destination: "/developer/", permanent: true },
  { source: "/developer/pride-purple-group", destination: "/developer/", permanent: true },
  { source: "/developer/mahindra-lifespaces", destination: "/developer/", permanent: true },
  { source: "/home-interiors", destination: "/", permanent: true },
  { source: "/developer/ashiana-housing-limited", destination: "/developer/", permanent: true },
  { source: "/developer/puravankara-limited", destination: "/developer/", permanent: true },
  { source: "/developer/pharande-spaces", destination: "/developer/", permanent: true },
  { source: "/developer/mapsko-group", destination: "/developer/", permanent: true },
  { source: "/developer/k-raheja-corp", destination: "/developer/", permanent: true },
  { source: "/property-in-delhi", destination: "/", permanent: true }, // Assuming redirect to home or valid path
  {
    source: "/developer/conscient-infrastructure-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/developer/kumar-properties", destination: "/developer/", permanent: true },
  { source: "/developer/central-park", destination: "/developer/", permanent: true },
  { source: "/developer/zen-realty-india", destination: "/developer/", permanent: true },
  { source: "/developer/gera-developments", destination: "/developer/", permanent: true },
  { source: "/developer/lodha-group", destination: "/developer/", permanent: true },
  { source: "/developer/bhutani-infra", destination: "/developer/", permanent: true },
  { source: "/developer/imperia-structures-limited", destination: "/developer/", permanent: true },
  { source: "/developer/ace-group", destination: "/developer/", permanent: true },
  {
    source: "/developer/pareena-infrastructures-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/developer/prateek-group", destination: "/developer/", permanent: true },
  { source: "/developer/emaar-properties", destination: "/developer/", permanent: true },
  {
    source: "/developer/duville-estates-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/developer/saan-group", destination: "/developer/", permanent: true },
  { source: "/developer/whiteland-corporation", destination: "/developer/", permanent: true },
  { source: "/developer/m3m-india", destination: "/developer/", permanent: true },
  { source: "/developer/hero-realty-private-limited", destination: "/developer/", permanent: true },
  {
    source: "/developer/pyramid-infratech-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/developer/max-estates", destination: "/developer/", permanent: true },
  { source: "/developer/tribeca-developers", destination: "/developer/", permanent: true },
  { source: "/faq", destination: "/", permanent: true },
  { source: "/developer/horizon-developers", destination: "/developer/", permanent: true },
  { source: "/developer/4s-developers", destination: "/developer/", permanent: true },
  { source: "/developer/dlf-home-developers-limited", destination: "/developer/", permanent: true },
  { source: "/developer/ats-infrastructure-limited", destination: "/developer/", permanent: true },
  { source: "/developer/kakkad-group", destination: "/developer/", permanent: true },
  { source: "/developer/saheel-properties", destination: "/developer/", permanent: true },
  {
    source: "/developer/adore-realtech-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/lowrise-properties", destination: "/", permanent: true },
  { source: "/commercial-properties", destination: "/", permanent: true },
  { source: "/developer/tata-housing", destination: "/developer/", permanent: true },
  { source: "/property-in-noida", destination: "/property-listing/city/noida", permanent: true },
  { source: "/developer/goel-ganga-developments", destination: "/developer/", permanent: true },
  { source: "/developer/krisumi-corporation", destination: "/developer/", permanent: true },
  { source: "/developer/paranjape-schemes-ltd", destination: "/developer/", permanent: true },
  { source: "/developer/gk-associates", destination: "/developer/", permanent: true },
  { source: "/developer/signature-global", destination: "/developer/", permanent: true },
  { source: "/developer/majestique-landmarks", destination: "/developer/", permanent: true },
  { source: "/developer/shapoorji-pallonji-group", destination: "/developer/", permanent: true },
  { source: "/developer/vtp-realty", destination: "/developer/", permanent: true },
  { source: "/developer/shree-sonigara-realcon", destination: "/developer/", permanent: true },
  { source: "/developer/birla-estates", destination: "/developer/", permanent: true },
  { source: "/developer/samridhi-group", destination: "/developer/", permanent: true },
  { source: "/developer/landmark-group", destination: "/developer/", permanent: true },
  {
    source: "/developer/orchid-infrastructure-developers-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/developer/eldeco-group", destination: "/developer/", permanent: true },
  { source: "/developer/rohan-builders", destination: "/developer/", permanent: true },
  { source: "/developer/suncity-projects-pvt-ltd", destination: "/developer/", permanent: true },
  { source: "/property-buying", destination: "/", permanent: true },
  { source: "/developer/sobha-limited", destination: "/developer/", permanent: true },
  { source: "/developer/navraj-infratech", destination: "/developer/", permanent: true },
  { source: "/developer/pride-group", destination: "/developer/", permanent: true },
  { source: "/developer/godrej-properties", destination: "/developer/", permanent: true },
  { source: "/developer/naiknavare-developers", destination: "/developer/", permanent: true },
  { source: "/developer/vilas-javdekar-developers", destination: "/developer/", permanent: true },
  { source: "/property-management-services", destination: "/", permanent: true },
  { source: "/developer/bptp-limited", destination: "/developer/", permanent: true },
  { source: "/property-in-gurugram", destination: "/", permanent: true },
  { source: "/developer/mantra-properties", destination: "/developer/", permanent: true },
  { source: "/developer/ss-group", destination: "/developer/", permanent: true },
  { source: "/developer/pristine-properties", destination: "/developer/", permanent: true },
  { source: "/developer/tarc-limited", destination: "/developer/", permanent: true },
  { source: "/developer/ambience-group", destination: "/developer/", permanent: true },
  { source: "/developer/experion-developers", destination: "/developer/", permanent: true },
  {
    source: "/developer/trehan-home-developers-private-limited",
    destination: "/developer/",
    permanent: true,
  },
  {
    source: "/developer/kolte-patil-developers-limited",
    destination: "/developer/",
    permanent: true,
  },
  { source: "/developer/panchsheel-group", destination: "/developer/", permanent: true },
  { source: "/developer/gygy-group", destination: "/developer/", permanent: true },
  { source: "/developer/brahma-group", destination: "/developer/", permanent: true },
  { source: "/developer/kohinoor-group", destination: "/developer/", permanent: true },
  { source: "/developer/chaphalkar-karandikar", destination: "/developer/", permanent: true },
  { source: "/blog/category/PR", destination: "/blog/", permanent: true },
  { source: "/blog/kolte-patil-springshire-wagholi-pune", destination: "/blog/", permanent: true },
  { source: "/blog/category/news", destination: "/blog/", permanent: true },
  { source: "/blog/category/article", destination: "/blog/", permanent: true },
  { source: "/buy/real-estate-in-gurugram", destination: "/", permanent: true },
  { source: "/blog/forth-slide-momentum-to-stay-strong", destination: "/blog/", permanent: true },
  { source: "/blog/category/PressRelease", destination: "/blog/", permanent: true },
  {
    source: "/property-listing/Hero Homes",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Puri Construction",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Emaar Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Adore Build Projects LLP",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Paras Buildtech",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Gera Developments",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Kolte Patil Developers Limited",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Signature Global Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Adani Realty",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/4S Developer Pvt. Ltd.",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Trevoc Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/TS Realtech",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Ganga Reality",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Conscient",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/SAAN Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/BPTP Limited",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Prestige Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Landmark Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Tulip Infratech",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Smart World Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Shapoorji Pallonji",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Sobha Ltd",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Godrej Properties",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Suncity Projects",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Experion Developers",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Krisumi Corporation",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Pioneer Urban",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Vatika Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Amrapali Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/SS group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Silverglades Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Bestech Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Whiteland Corporations",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/DLF Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Mapsko Builders",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/TATA Housing",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Orchid Infrastructure Developers Private Limited",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Prateek Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Kalpataru Limited",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Saheel Properties",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Majestique Landmarks",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Pristine Properties",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Ambience Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Mantra Properties",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/TARC Limited",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Imperia Structures Ltd",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Ace Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/Pyramid Infratech Private Limited",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property-listing/M3M India",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },

  {
    source: "/property-listing/Lodha Group",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },

  {
    source: "/buy/real-estate-in-pune",
    destination: "/property-listing/city/pune",
    permanent: true,
  },
  { source: "/buy/flats-in-pune", destination: "/property-listing/city/pune", permanent: true },
  { source: "/blog/category/infra-times", destination: "/blog/", permanent: true },
  { source: "/buy/new-projects-in-delhi", destination: "/", permanent: true },
  { source: "/buy/new-projects-in-pune", destination: "/", permanent: true },
  {
    source: "/buy/flats-in-gurugram",
    destination: "/property-listing/city/Gurgaon",
    permanent: true,
  },
  { source: "/buy/new-projects-in-gurugram", destination: "/", permanent: true },
  { source: "/pr/[media]", destination: "/", permanent: true },
  {
    source: "/locality",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  { source: "/price-vs-size", destination: "/", permanent: true },
  { source: "/villa-properties", destination: "/", permanent: true },
  { source: "/property-in-pune", destination: "/property-listing/city/pune", permanent: true },
  {
    source: "/property",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/blog/iffco-chowk-metro-station-gurgaon-key-areas-amenities-and-faqs",
    destination: "/blog",
    permanent: true,
  },
  {
    source: "/property/dlf-alameda-sector-73-gurugram",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property/dlf-arbour-sector-63-gurgaon",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property/dlf-regal-gardens-sector-90-gurgaon",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property/dlf-privana-west-sector-76-gurgaon",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property/dlf-privana-south-sector-77-gurgaon",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property/dlf-park-place-sector-54-gurgaon",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/property/dlf-privana-north-sector-76-gurgaon",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },

  // Routes removed from the codebase. They were live and returning 200, so they
  // keep 301ing rather than starting to 404 — /explore/city keeps its city so a
  // visitor lands on the same city's listing.
  { source: "/explore/city/:name", destination: "/property-listing/city/:name", permanent: true },
  {
    source: "/explore/state",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/top-cities",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  {
    source: "/listing",
    destination: "/property-listing/search/property-in-india",
    permanent: true,
  },
  // /locality/:name was a second, unlinked locality-listing route. The live
  // equivalent is /property-listing/locality/:name, so the locality carries over
  // instead of the URL starting to 404.
  {
    source: "/locality/:name",
    destination: "/property-listing/locality/:name",
    permanent: true,
  },
];
